spring:
  application:
    name: iasmin-asterisk-ari
  threads:
    virtual:
      enabled: true
  servlet:
    multipart:
      max-file-size: 6MB
      max-request-size: 6MB

server:
  tomcat:
    max-http-form-post-size: 6MB

ari:
  host: "${ARI_HOST}"
  user: "${ARI_USER}"
  password: "${ARI_PASSWORD}"
  outbound-app-name: "${ARI_APP_OUTBOUND_NAME}"
  inbound-app-name: "${ARI_APP_INBOUND_NAME}"

ami:
  host: "${AMI_HOST}"
  user: "${AMI_USER}"
  password: "${AMI_PASSWORD}"

asterisk:
  config: "${ASTERISK_CONFIG}"

pabx:
  trunk: "${PABX_TRUNK}"
  tech-prefix: "${PABX_TECH_PREFIX}"

audio:
  record: "${AUDIO_RECORD}"
  moh: "${AUDIO_MOH}"

iasmin:
  backend-api: "${IASMIN_BACKEND_API}"

jwt:
  secret: "${JWT_SECRET}"
